plugins {
    id 'java-library'
    id 'distribution'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

dependencies {
    // this will be provided by the workflow-bot application
    compileOnly project(':workflow-language')

    // a third party library used by the custom activity
    // it will be packaged along with this project
    implementation 'org.apache.commons:commons-text:1.10.0'
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.11.4")
    testImplementation("org.mockito:mockito-core:5.15.2")
    testImplementation("com.diffblue.cover:cover-annotations:1.3.0")
    testImplementation("org.hamcrest:hamcrest:3.0")
}

// package the activity and its dependencies so it can be added to a workflow-bot application
distributions {
    main {
        contents {
            into('lib') {
                from jar
                from(project.configurations.runtimeClasspath)
            }
        }
    }
}
